import rainJacket from "./assets/rain-jacket.jpg";
import moonlightDress from "./assets/moonlight-dress.jpg";
import merlotSuit from "./assets/merlot-suit.jpg";

export const DummyProducts = [
  {
    name: "przedmiot1",
    description: "to jest opis pierwszego przedmiotu",
    price: 20.99,
    image: rainJacket,
    amount: 5,
    user: "user1",
    endDate: "29.12.2023",
    id: "1",
    qr: "Tu ma być kod qr",
  },
  {
    name: "przedmiot2",
    description: "to jest opis drugiego przedmiotu",
    price: 15.52,
    image: moonlightDress,
    amount: 2,
    user: "user2",
    endDate: "25.12.2023",
    id: "2",
    qr: "Tu ma być kod qr",
  },
  {
    name: "przedmiot3",
    description: "To jest opis trzeciego przedmiotu",
    price: 25.51,
    image: merlotSuit,
    amount: 10,
    user: "user4",
    endDate: "31.12.2023",
    id: "3",
    qr: "Tu ma być kod qr",
  },
  {
    name: "przedmiot4",
    description: "To jest opis czwartego przedmiotu",
    price: 29.55,
    image: merlotSuit,
    amount: 10,
    user: "user5",
    endDate: "31.12.2023",
    id: "4",
    qr: "Tu ma być kod qr",
  },
  {
    name: "przedmiot5",
    description: "To jest opis piątego przedmiotu",
    price: 22.55,
    image: merlotSuit,
    amount: 10,
    user: "user6",
    endDate: "31.12.2023",
    id: "5",
    qr: "Tu ma być kod qr",
  },
];
