# Generated by Django 5.0 on 2024-01-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
