# Generated by Django 5.0 on 2024-01-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_delete_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='avaible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
